name: Sync to GitLab

on:
  push:
    branches:
      - main # or the branch you want to monitors

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Push to GitLab
      env:
        GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        GITLAB_REPO_URL: ${{ secrets.GITLAB_REPO_URL }}
      run: |
    
        git config --global user.name "Pankaj-Kamate"
        git config --global user.email "pankajkamate@gmail.com"
    
    
        git remote add gitlab https://${GITLAB_TOKEN}@${GITLAB_REPO_URL#https://}
        git push --force --set-upstream gitlab HEAD:main
