name: Sync to GitLab

on:
  push:
    branches:
      - main # or the branch you want to monitor

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Push to GitLab
      env:
        GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN_LAB }}
        GITLAB_REPO_URL: ${{ secrets.GITLAB_REPO_URL_HUB }}
      run: |
        git remote add gitlab $GITLAB_REPO_URL_HUB
        git push --force --set-upstream gitlab HEAD:main # Adjust branch as needed
