- name: Push to GitLab
  env:
    GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
    GITLAB_REPO_URL: ${{ secrets.GITLAB_REPO_URL }}
  run: |
    # Set Git credentials
    git config --global user.name "Pankaj-Kamate"
    git config --global user.email "pankajkamate@gmail.com"
    
    # Add and push to GitLab remote
    git remote add gitlab https://${GITLAB_TOKEN}@${GITLAB_REPO_URL#https://}
    git push --force --set-upstream gitlab HEAD:main
