name: Sync to GitLabs

on:
  push:
    branches:
      - main # or the branch you want to monitors

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Push to GitLab
      env:
        GITLAB_TOKEN_LAB: ${{ secrets.GITLAB_TOKEN_LAB }}
        GITLAB_REPO_URL_HUB: ${{ secrets.GITLAB_REPO_URL_HUB }}
      run: |
    
        git config --global user.name "Pankaj-Kamate"
        git config --global user.email "pankajkamate@gmail.com"
        git remote add gitlab https://${GITLAB_REPO_URL_HUB#https://}:${GITLAB_TOKEN_LAB}@gitlab.com/${GITLAB_REPO_URL_HUB#https://gitlab.com/}
        #git remote add gitlab https://gitlab-ci-token:${GITLAB_TOKEN_LAB}@${GITLAB_REPO_URL_HUB}
        git push --force --set-upstream gitlab HEAD:main
        #GITLAB_URL_WITH_TOKEN=${GITLAB_REPO_URL/https:\/\//https:\/\/gitlab-ci-token:${GITLAB_TOKEN}@}
        #git remote add gitlab $GITLAB_URL_WITH_TOKEN
        #git push --force gitlab HEAD:main
